name: Step 1
on:
  push:
    branches:
      - main
    paths:
      - 'cmake/Step1/**'
      - '.github/workflows/build-step1.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'cmake/Step1/**'
      - '.github/workflows/build-step1.yml'
jobs:
  Step1:
    name: Step 1
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build # Directory where build-wrapper output will be placed

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6

      - name: Run Build Wrapper
        working-directory: Step1
        run: |
          rm -fr ${{ env.BUILD_WRAPPER_OUT_DIR }}
          cmake -S . -B ${{ env.BUILD_WRAPPER_OUT_DIR }}
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build ${{ env.BUILD_WRAPPER_OUT_DIR }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Put the name of your token here
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ github.job }}/${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json
          projectBaseDir: cmake/Step1